# Generated by Django 3.2.9 on 2021-12-01 16:01

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20211201_1114'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Editor',
            new_name='User',
        ),
        migrations.AlterField(
            model_name='article',
            name='post',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(to='news.tags'),
        ),
    ]
